FROM ubuntu:24.04


ENV DEBIAN_FRONTEND=noninteractive

# ---------------------------------------------------------------------------
# System dependencies
# ---------------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    ninja-build \
    g++ \
    libpcap-dev \
    libcap-dev \
    libcap2-bin \
    && rm -rf /var/lib/apt/lists/*


# RUN apt-get update && apt-get install -y --no-install-recommends \
#     librabbitmq-dev \
#     && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY . .

RUN cmake --preset docker && \
    cmake --build --preset docker

# ---------------------------------------------------------------------------
# Entrypoint — added Day 20 when full pipeline is wired
# ---------------------------------------------------------------------------
# ENTRYPOINT ["./build/docker/packet-engine"]


CMD ["./build/docker/packet-engine"]