name: CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  cpp-build:
    name: C++ Build + Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
 
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build g++ \
            libpcap-dev \
            libcap-dev \
            librabbitmq-dev

      - name: Configure 
        working-directory: cpp-packet-engine 
        run: cmake --preset ci
 
      - name: Build 
        working-directory: cpp-packet-engine
        run: cmake --build --preset ci
        
      - name: Test
        working-directory: cpp-packet-engine
        run: ctest --preset ci --output-on-failure